---
# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

APPLY_FIXES: all # all, none, or list of linter keys

# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling-formats will be disabled by default
# ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
DISABLE:
  - COPYPASTE # excessive copy-pastes
  - SPELL # spelling mistakes
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
FLAVOR_SUGGESTIONS: true # suggest smaller flavors if available
ADDITIONAL_EXCLUDED_DIRECTORIES:
  - ".ruff_cache" # exclude ruff cache files
  - ".venv" # exclude virtualenv files
EDITORCONFIG_EDITORCONFIG_CHECKER_FILTER_REGEX_EXCLUDE: ".pylintrc"
# DISABLE_ERRORS: true # Uncomment if you want MegaLinter to detect errors but not block CI to pass
