---
name: Test
on:
  push: {}

concurrency:
  group: ${{ github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true
  # cancel-in-progress: ${{ github.ref_name != github.event.repository.default_branch }} # Cancel previous runs if new one is triggered on non-default branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup direnv
        uses: HatsuneMiku3939/direnv-action@v1
        with:
          direnvVersion: 2.32.2
      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: "3.11"
      - name: setup poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.6.1
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: install dependencies
        run: |
          poetry install --no-root
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root
      - name: Install project
        run: poetry install --no-interaction
      - name: Test set-tap
        shell: bash
        run: |
          # exit if subcommands exit
          set -e

          TAP="nsheaps/homebrew-devsetup"
          # exit 1 if "$(devsetup get-tap)" != ""
          if [[ "$(devsetup get-tap)" != "" ]]; then
            echo "❌ get-tap is not empty on initial config"
            exit 1
          fi

          if ! devsetup set-tap $TAP; then
            echo "❌ set-tap failed"
            exit 1
          fi

          # exit 1 if "$(devsetup get-tap)" != "$TAP"
          if [[ "$(devsetup get-tap)" != "$TAP" ]]; then
            echo "❌ get-tap is not $TAP"
            exit 1
          fi

          echo "✅ set-tap worked properly"
